### ISSUE TITLE
final training results?

### ISSUE THREAD

**Issue by LightToYang** [DeNA/PyTorch_YOLOv3#20]
I find all the data augmentation methods are done, so wiil the final training results be released for comparison with the original training results?

**Comment by hirotomusiker** [comment]
Thank you!
We are running the final training with all the augmentation.
Please wait a little bit more for the release of the results.

**Comment by geminikq** [comment]
I ran the latest version of your implementation for one epoch, but got 0 map. it seems that the random distortion to be the problem. I don't know if you guys ran into it.

**Comment by hirotomusiker** [comment]
Oh this is a bug.
We have made https://github.com/DeNA/PyTorch_YOLOv3/pull/21 to fix it.

**Comment by hirotomusiker** [comment]
Thank you for reporting it! We are checking the feature again.

**Comment by hirotomusiker** [comment]
We have verified that the bug is fixed by https://github.com/DeNA/PyTorch_YOLOv3/pull/21 . 
Please try again with the latest commit. @geminikq

**Comment by geminikq** [comment]
@hirotomusiker 
Oh, I pulled again and saw the update, it seems you just merged to master? hmm, weired..
Anyway, I will try it again, thanks guys.

**Comment by benjaminjack** [comment]
Was anyone able to match the original paper results? I'm trying to match the results with augmentation and it doesn't seem to be performing any better than with just random resizing.

**Comment by hirotomusiker** [comment]
Let me share the results we know so far :

- COCO AP 50:95 is around 0.275 after the lr drop at 200k iter with random resizing, random placing and LR flip (ref: 0.302 with our repo and author's weight)
- random placing and / or LR flip improves the AP by 3-4% before the lr drop
- still unclear if random distortion works or not
- increasing batch size improves the results. The author's batch-size condition for paper results is unclear

Thank you.

**Comment by hirotomusiker** [comment]
We have found that the AP results written in the original paper have been measured using the **COCO train-val for training (123K data) and test-dev (20K data) for validation**, which is different from our settings (118K for train and 5K for val).
We CANNOT reach the paper results with the 118K / 5K settings - but our repo reproduces darknet **on the same dataset settings.**

**Comment by hirotomusiker** [comment]
We will release the val results of darknet and ours for the 118K / 5K split soon.
Let us close the issue for now.

**Comment by sisrfeng** [comment]
> increasing batch size improves the results. The author's batch-size condition for paper results is unclear

Hi, I am testing the repo on another dataset. The image size is 1920×1080. The training set contains 2k  images. What batch size do you think is the best？
What if  the training set contains 60k  images？
Many thanks!
