### ISSUE TITLE
distributed training in pytorch 1.0

### ISSUE THREAD

**Issue by LightToYang** [DeNA/PyTorch_YOLOv3#23]
It seems the training is doing with single gpu, do you have any plan about multi-gpus training like distributed trianing in pytorch 1.0?

**Comment by hirotomusiker** [comment]
We don't have a plan of releasing the training optimized for multiple gpus right now.
Thank you.

**Comment by hirotomusiker** [comment]
Although not optimized, you can use multi-GPUs if you insert the following code at
https://github.com/DeNA/PyTorch_YOLOv3/blob/70e9dab0bec1e46fab8888914e311f953d989056/train.py#L94

```
model = torch.nn.DataParallel(model)
```

**Comment by sisrfeng** [comment]
> Although not optimized, you can use multi-GPUs if you insert the following code at
> https://github.com/DeNA/PyTorch_YOLOv3/blob/master/train.py#L94
> 
> ```
> model = torch.nn.DataParallel(model)
> ```

Is distributed testing the same ?

**Comment by hirotomusiker** [comment]
Unfortunately we have not tried it on our repo.

**Comment by sisrfeng** [comment]
> Although not optimized, you can use multi-GPUs if you insert the following code at
> https://github.com/DeNA/PyTorch_YOLOv3/blob/master/train.py#L94
> 
> ```
> model = torch.nn.DataParallel(model)
> ```

Do you mean this？
```
   elif args.checkpoint:
        print("loading pytorch ckpt...", args.checkpoint)
        model = torch.nn.DataParallel(model,device_ids=[0,1,2,3,4,5,6,7])
        state = torch.load(args.checkpoint)
        if 'model_state_dict' in state.keys():
```
Then if I run
`python train.py --cfg config/gaussian_yolov3_default.cfg --weights_path weights/darknet53.conv.74 --tfboard_dir ./log`
Then we can't use muti gpus.

if I run
 `python train.py --cfg config/gaussian_yolov3_default.cfg  --checkpoint checkpoints/snapshot1000.ckpt  --tfboard_dir ./log`
Then：
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.module_list.0.conv.weight",  （and so on）
         Unexpected key(s) in state_dict: "module_list.0.conv.weight",（and so on）
Could you please tell me how to fix it？

**Comment by sisrfeng** [comment]
If inset like this:
```
elif args.checkpoint:
        print("loading pytorch ckpt...", args.checkpoint)
        state = torch.load(args.checkpoint)
        model = torch.nn.DataParallel(model,device_ids=[0,1,2,3,4,5,6,7])
        if 'model_state_dict' in state.keys():
```
and run this
`python train.py --cfg config/gaussian_yolov3_default.cfg --checkpoint checkpoints/snapshot1000.ckpt --tfboard_dir ./log`

```
Error：
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 118, in main
    model.load_state_dict(state['model_state_dict'])
  File "/home/docker/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.module_list.0.conv.wei
```

**Comment by hirotomusiker** [comment]
Oh I think the line number is wrong now because the code has been changed.
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/train.py#L94
should be:
https://github.com/DeNA/PyTorch_YOLOv3/blob/70e9dab0bec1e46fab8888914e311f953d989056/train.py#L94

**Comment by sisrfeng** [comment]
Thank you!
Some more changes are needed:
1:
File "train.py", line 214, in main
loss.backward()
should be  loss.sum().backward()

2:
Notably, if you use 'DataParallel', the model will be wrapped in DataParallel(). It means you need to change the model.function() to model.module.function() in the following codes.
For example,
model.train_model --> model.module.train_model
 https://github.com/jytime/Mask_RCNN_Pytorch/issues/2#issuecomment-423718196

**Comment by sisrfeng** [comment]
After the changes above, other error accur...

**Comment by tjiagoM** [comment]
> 
> 
> After the changes above, other error accur...

@sisrfeng I'm trying to adapt to multiple GPUs using DataParallel but I'm also getting some errors with the changes. I wonder if you'd be able to share what other errors you got and how you solve them? Thanks!

**Comment by tjiagoM** [comment]
For example, I've noticed that the `loss_dict` construction is a problem as now instead of being calculated in a single model is being calculated across multiple GPUs, so was curious to see how you did it!

**Comment by sisrfeng** [comment]
Sorry，but it has been too long for me to remember the error.
May be  I end up with using a single GPU...
