### ISSUE TITLE
demo script causes error when no object was detected

### ISSUE THREAD

**Issue by yu4u** [DeNA/PyTorch_YOLOv3#24]
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/demo.py#L74

`outputs[0]` becomes `[None]` when there is no object found.

**Comment by hirotomusiker** [comment]
Thank you for reporting it!
Please look at the following PR:
https://github.com/DeNA/PyTorch_YOLOv3/pull/25

**Comment by yu4u** [comment]
THX!
