### ISSUE TITLE
Hello,I have a question about this code!

### ISSUE THREAD

**Issue by BCWang93** [DeNA/PyTorch_YOLOv3#30]
Why do you use this "x2 = (labels[:, 1] + labels[:, 3]) / w
                                 y2 = (labels[:, 2] + labels[:, 4]) / h'' of the 'label2yolobox function' in the 'utils.py',I think it thats some error? Can you tell me this is why?Thank you very much!

**Comment by hirotomusiker** [comment]
Oh I just have noticed that the description in the docstring is wrong.
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/utils/utils.py#L175-L177
The input COCO label has the annotation [x1, y1, w, h] and the code you have mentioned converts it to [x1, y1, x2, y2]. I will fix the description. Thank you.

**Comment by hirotomusiker** [comment]
corrected by https://github.com/DeNA/PyTorch_YOLOv3/pull/32.
