### ISSUE TITLE
Isn't it necessary to fix checkpoint corrections in demo.py as well?

### ISSUE THREAD

**Issue by pal-uchi** [DeNA/PyTorch_YOLOv3#34]
Loading "weight" from a checkpoint with "demo.py" will fail.
Don't you need to fix  "Merge pull request #28 from DeNA/feature/full_checkpoint " to "demo.py" as well.

'''
        model.load_state_dict(torch.load(args.ckpt))
        state = torch.load(args.ckpt)
        if 'model_state_dict' in state.keys():
            model.load_state_dict(state['model_state_dict'])
        else:
            model.load_state_dict(state)
'''

**Comment by hirotomusiker** [comment]
Exactly. Thank you for pointing it out.
We have started to fix it at:
https://github.com/DeNA/PyTorch_YOLOv3/pull/35
