### ISSUE TITLE
Question about data preprocess

### ISSUE THREAD

**Issue by eleflea** [DeNA/PyTorch_YOLOv3#41]
Hi, I found several confusing codes in data preprocess part.
- in cocodataset.py, line 87, `img = cv2.imread(img_file)`. As far as I know, opencv reads image in BGR, but in `random_distort` function, you treats it as RGB mode, use `cv2.COLOR_RGB2HSV`
- in `preprocess` function of utils.py, you simply use 127 for 3 channels, is it better to use mean color here?
- in `yolobox2label` function of utils.py, I think there is a fault in doc string about box, it might should be [y1, x1, y2, x2] in [0, 1]?

**Comment by molyswu** [comment]
Do you have horovod distributed training code?

**Comment by hirotomusiker** [comment]
Thank you and sorry for the delayed response.

> opencv reads image in BGR, but in random_distort function, you treats it as RGB mode

We convert an image to RGB mode right after imread.
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/utils/utils.py#L250

>simply use 127 for 3 channels

Other popular frameworks like R-CNN family use mean color of the dataset, but we follow the preprocess of darknet.

> there is a fault in doc string about box,

Indeed there is. We will fix the docstring later!

**Comment by eleflea** [comment]
Thank you for solving my doubts, and thank you for your maintenance of this project.
