### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator,

### ISSUE THREAD

**Issue by molyswu** [DeNA/PyTorch_YOLOv3#42]
File "train.py", line 172, in main
    loss = model(imgs, targets)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)

 return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

**Comment by mese79** [comment]
Hi
Did you solve this issue? how?

**Comment by kouohhashi** [comment]
I'm having same issue.
Could you solve this problem without downgrading pytorch?
