### ISSUE TITLE
 if 'optimizer_state_dict' in state.keys():

### ISSUE THREAD

**Issue by molyswu** [DeNA/PyTorch_YOLOv3#43]
Hi,
python train.py   --cfg config/yolov3_default.cfg  --weight /media/yolov3-pytoch/PyTorch-YOLOv3/weights/yolov3.weights  --n_cpu  0 --checkpoint_interval 1000 --eval_interval 4000 --checkpoint str --checkpoint_dir ./checkpoints/

Traceback (most recent call last):
  File "train.py", line 213, in <module>
    main()
  File "train.py", line 145, in main
    if 'optimizer_state_dict' in state.keys():
UnboundLocalError: local variable 'state' referenced before assignment

**Comment by hirotomusiker** [comment]
Thank you for reporting the issue.
Could you just drop ` --checkpoint str ` from your training command?
