### ISSUE TITLE
Error when training yolo on my dataset:IndexError: index 69 is out of bounds for dimension 3 with size 68

### ISSUE THREAD

**Issue by BucolicWind** [DeNA/PyTorch_YOLOv3#50]
I want to use yolo on my dataset ,and there are 10 classes.I changed the N_CLASSES in data/yolov3_default.cfg to 10. Nothing else is changed.But I met the following error when training:
File "train.py", line 216, in <module>
    main()
  File "train.py", line 174, in main
    loss = model(imgs, targets)
  File "/home/omnisky/.conda/envs/dw/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/omnisky/dongwei/PyTorch_YOLOv3/models/yolov3.py", line 154, in forward
    x, *loss_dict = module(x, targets)
  File "/home/omnisky/.conda/envs/dw/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/omnisky/dongwei/PyTorch_YOLOv3/models/yolo_layer.py", line 164, in forward
    obj_mask[b, a, j, i] = 1
IndexError: index 69 is out of bounds for dimension 3 with size 68
I would be appreciated if you can help me to solve this problem. waiting for you reply,thank you.

**Comment by BucolicWind** [comment]
Usually, this error happened when iteration has been gone for 300-400 batches.

**Comment by hirotomusiker** [comment]
Hi, it’s possible that the label of your dataset has a bounding box whose center is out of the image. Could you check the label when the error occurs?

**Comment by BucolicWind** [comment]
The dataset I used was Visdrone, have you ever been train yolo on this dataset?And if I filtered the bbox whose center is out of the image, and will this error been solved? Thanks for your reply

**Comment by hirotomusiker** [comment]
Unfortunately I haven't tried Visdrone.
I'm not 100% sure but I think it comes from one of the dataset labels. Thank you
