### ISSUE TITLE
how much time do you cost for training with pretrained model? and what the GPU you used? 

### ISSUE THREAD

**Issue by linhezheng19** [DeNA/PyTorch_YOLOv3#51]

**Comment by hirotomusiker** [comment]
We have described the training speed and GPU spec here:
https://github.com/DeNA/PyTorch_YOLOv3#training

We use a single V100 GPU and the speed is 19.4 iters / min. So for 500k iterations it takes 17-18 days.

**Comment by hirotomusiker** [comment]
If you are training a smaller dataset than COCO or if you don't need 1% extra AP, I recommend to set the training schedule shorter.
