### ISSUE TITLE
class YOLOV3 forward function return error when using costumed data

### ISSUE THREAD

**Issue by billchenxi** [DeNA/PyTorch_YOLOv3#53]
When I using my own dataset the model return error 
```
 x = torch.cat((x, route_layers[1]), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 15 and 16 in dimension 2
```
The `x` shape is `torch.Size([4, 256, 16, 16])`
and the `rout_layer[1]` is `torch.Size([4, 512, 15, 15])`.

Why the last two dimensions number is 15?

**Comment by hirotomusiker** [comment]
Thank you. 
Could you check if your original images are passed to the preprocess
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/dataset/cocodataset.py#L95-L96
and if the target image size is divisible by 32?
