### ISSUE TITLE
Difference between  .ckpt and .pt files

### ISSUE THREAD

**Issue by sisrfeng** [DeNA/PyTorch_YOLOv3#57]
I am a beginner. Would you mind telling me why you use .ckpt files rather than .pt files here？
       ```
 # save checkpoint
        if args.checkpoint_dir and iter_i > 0 and (iter_i % args.checkpoint_interval == 0):
            torch.save({'iter': iter_i,
                        'model_state_dict': model.state_dict(),
                        'optimizer_state_dict': optimizer.state_dict(),
                        },
                        os.path.join(args.checkpoint_dir, "snapshot"+str(iter_i)+".ckpt"))
```
I find this in pytorch document:
>>> torch.load('tensors.pt')
# Load all tensors onto the CPU
>>> torch.load('tensors.pt', map_location=lambda storage, loc: storage)

Are .ckpt files originally used in tensorflow but similar with .pt files in pytorch？
Thank you!

**Comment by hirotomusiker** [comment]
Thank you.
You can name the checkpoint file as .pt or .pth instead of .ckpt.
