### ISSUE TITLE
About the backbone 

### ISSUE THREAD

**Issue by eric612** [DeNA/PyTorch_YOLOv3#7]
Thanks for your awesome work , I have some questions about backbone:

* I search the whole project and can not find the backbone weights loading point. How can I change the backbone weights , for example , I want use coco as pre-trained weights instead of darknet53.conv.74

* Did you have plan to support yolov3-tiny ?

**Comment by hirotomusiker** [comment]
Hi, thank you for using our repo!

-  The function 'parse_yolo_weights(model, weights_path)' can load pretrained weights on the model. https://github.com/DeNA/PyTorch_YOLOv3/blob/master/utils/parse_yolo_weights.py
As long as the model definition and the weights match, you can load any weights files such as yolov3.weights . 

We call the function like this:
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/demo.py#L53-L55

-  Right now I am completing data augmentation modules. I will add yolov3-tiny to the Todo list.

**Comment by eric612** [comment]
It works , thanks a lot
